/**
 * Browse saved-search CTA event surface.
 */
export {
  BROWSE_RECENTS_PANEL_SURFACE,
  BROWSE_RESULTS_SURFACE,
  BROWSE_SAVED_SEARCH_MANAGER_SURFACE,
  BROWSE_SAVED_SEARCH_SURFACE,
  browseEmptySuggestionApplyAnalyticsData,
  browseEmptySuggestionApplyAnalyticsEvent,
  browseLoadMoreAnalyticsData,
  browseLoadMoreAnalyticsEvent,
  browseRecentEntryClickAnalyticsData,
  browseRecentEntryClickAnalyticsEvent,
  browseSavedSearchApplyAnalyticsData,
  browseSavedSearchApplyAnalyticsEvent,
  browseSavedSearchLinkClickAnalyticsData,
  browseSavedSearchLinkClickAnalyticsEvent,
  browseSavedSearchManagerAlertsCancelAnalyticsData,
  browseSavedSearchManagerAlertsCancelAnalyticsEvent,
  browseSavedSearchManagerAlertsEditorAnalyticsData,
  browseSavedSearchManagerAlertsEditorAnalyticsEvent,
  browseSavedSearchManagerAlertsSaveAnalyticsData,
  browseSavedSearchManagerAlertsSaveAnalyticsEvent,
  browseSavedSearchManagerAlertsToggleAnalyticsData,
  browseSavedSearchManagerAlertsToggleAnalyticsEvent,
  browseSavedSearchManagerApplyAnalyticsData,
  browseSavedSearchManagerApplyAnalyticsEvent,
  browseSavedSearchManagerCadenceSelectAnalyticsData,
  browseSavedSearchManagerCadenceSelectAnalyticsEvent,
  browseSavedSearchManagerChannelToggleAnalyticsData,
  browseSavedSearchManagerChannelToggleAnalyticsEvent,
  browseSavedSearchManagerFeedCopyAnalyticsData,
  browseSavedSearchManagerFeedCopyAnalyticsEvent,
  browseSavedSearchManagerOpenAnalyticsData,
  browseSavedSearchManagerOpenAnalyticsEvent,
  browseSavedSearchManagerRemoveAnalyticsData,
  browseSavedSearchManagerRemoveAnalyticsEvent,
  browseSavedSearchManagerRenameAnalyticsData,
  browseSavedSearchManagerRenameAnalyticsEvent,
  browseSavedSearchRemoveAnalyticsData,
  browseSavedSearchRemoveAnalyticsEvent,
  browseSavedSearchSaveAnalyticsData,
  browseSavedSearchSaveAnalyticsEvent,
  savedSearchFilterCount,
  type BrowseSavedSearchAlertCadence,
  type BrowseSavedSearchAlertChannel,
} from "@/lib/browse-saved-search-cta-events-lib";
