/**
 * Directory hub navigation CTA event surface.
 */
export {
  BEST_INDEX_SURFACE,
  CATEGORY_HUB_NOTFOUND_SURFACE,
  CATEGORY_HUB_SURFACE,
  PLATFORM_CATEGORY_NOTFOUND_SURFACE,
  PLATFORM_CATEGORY_SURFACE,
  PLATFORM_HUB_NOTFOUND_SURFACE,
  PLATFORM_HUB_SURFACE,
  PLATFORM_INDEX_SURFACE,
  bestIndexListAnalyticsData,
  bestIndexListAnalyticsEvent,
  categoryHubBrowseAnalyticsData,
  categoryHubBrowseAnalyticsEvent,
  categoryHubNotFoundEgressAnalyticsData,
  categoryHubNotFoundEgressAnalyticsEvent,
  categoryHubSeeAllAnalyticsData,
  categoryHubSeeAllAnalyticsEvent,
  platformCategoryCategoryAnalyticsData,
  platformCategoryCategoryAnalyticsEvent,
  platformCategoryNotFoundEgressAnalyticsData,
  platformCategoryNotFoundEgressAnalyticsEvent,
  platformCategoryPlatformAnalyticsData,
  platformCategoryPlatformAnalyticsEvent,
  platformHubBrowseAnalyticsData,
  platformHubBrowseAnalyticsEvent,
  platformHubNotFoundEgressAnalyticsData,
  platformHubNotFoundEgressAnalyticsEvent,
  platformHubSectionAnalyticsData,
  platformHubSectionAnalyticsEvent,
  platformIndexSelectAnalyticsData,
  platformIndexSelectAnalyticsEvent,
} from "@/lib/directory-hub-cta-events-lib";
