/**
 * Home page navigation CTA event surface.
 */
export {
  HOME_PAGE_SURFACE,
  homeBriefAnalyticsData,
  homeBriefAnalyticsEvent,
  homeBriefDestination,
  homeBrowseSearchDestination,
  homeCategorySelectAnalyticsData,
  homeCategorySelectAnalyticsEvent,
  homeCategorySelectDestination,
  homeCompareRailCtaAnalyticsData,
  homeCompareRailCtaAnalyticsEvent,
  homeCompareRailCtaDestination,
  homeContributeCtaAnalyticsData,
  homeContributeCtaAnalyticsEvent,
  homeContributeCtaDestination,
  homeHeroCtaAnalyticsData,
  homeHeroCtaAnalyticsEvent,
  homeHeroCtaDestination,
  homeHeroExampleSearchAnalyticsData,
  homeHeroExampleSearchAnalyticsEvent,
  homeIntentBrowseSearch,
  homeIntentSelectAnalyticsData,
  homeIntentSelectAnalyticsEvent,
  homePopularSearchAnalyticsData,
  homePopularSearchAnalyticsEvent,
  homePulseChangelogEgressAnalyticsData,
  homePulseChangelogEgressAnalyticsEvent,
  homePulseChangelogRowAnalyticsData,
  homePulseChangelogRowAnalyticsEvent,
  homePulseContributorClickAnalyticsData,
  homePulseContributorClickAnalyticsEvent,
  homePulseContributorsIndexAnalyticsData,
  homePulseContributorsIndexAnalyticsEvent,
  homeRailCtaAnalyticsData,
  homeRailCtaAnalyticsEvent,
  homeRailCtaDestination,
  homeTrustStatAnalyticsData,
  homeTrustStatAnalyticsEvent,
  homeTrustStatDestination,
  type HomeCompareRailCtaId,
  type HomeContributeCtaDestination,
  type HomeContributeCtaId,
  type HomeHeroCtaDestination,
  type HomeHeroCtaId,
  type HomeIntentBrowseSearch,
  type HomeTrustStatDestination,
  type HomeTrustStatId,
} from "@/lib/home-page-cta-events-lib";
