/**
 * Jobs hub navigation CTA event surface.
 */
export {
  JOBS_DETAIL_SURFACE,
  JOBS_INDEX_SURFACE,
  jobsDetailEgressAnalyticsData,
  jobsDetailEgressAnalyticsEvent,
  jobsDetailIndexAnalyticsData,
  jobsDetailIndexAnalyticsEvent,
  jobsDetailRelatedAnalyticsData,
  jobsDetailRelatedAnalyticsEvent,
  jobsDetailShareCopyAnalyticsData,
  jobsDetailShareCopyAnalyticsEvent,
  jobsErrorRetryAnalyticsData,
  jobsErrorRetryAnalyticsEvent,
  jobsIndexFilterClearAnalyticsData,
  jobsIndexFilterClearAnalyticsEvent,
  jobsIndexFilterSelectAnalyticsData,
  jobsIndexFilterSelectAnalyticsEvent,
  jobsIndexJobAnalyticsData,
  jobsIndexJobAnalyticsEvent,
  jobsIndexPostAnalyticsData,
  jobsIndexPostAnalyticsEvent,
  jobsIndexSortSelectAnalyticsData,
  jobsIndexSortSelectAnalyticsEvent,
  jobsIndexStatAnalyticsData,
  jobsIndexStatAnalyticsEvent,
  jobsIndexStatFilterPatch,
  type JobsDetailEgressDestination,
  type JobsDetailIndexSource,
  type JobsErrorSurface,
  type JobsIndexFilterAxis,
  type JobsIndexJobVariant,
  type JobsIndexPostSource,
  type JobsIndexSortMode,
  type JobsIndexStatFilterPatch,
  type JobsIndexStatId,
} from "@/lib/jobs-hub-cta-events-lib";
