/**
 * Resource card CTA event surface.
 */
export {
  RESOURCE_CARD_SURFACE,
  resourceCardBadgeKinds,
  resourceCardCategoryBrowseAnalyticsData,
  resourceCardCategoryBrowseAnalyticsEvent,
  resourceCardTrustBrowseAnalyticsData,
  resourceCardTrustBrowseAnalyticsEvent,
  resourceCardCompareAnalyticsData,
  resourceCardCompareAnalyticsEvent,
  resourceCardCompareToastOpenAnalyticsData,
  resourceCardCompareToastOpenAnalyticsEvent,
  resourceCardEntryAnalyticsData,
  resourceCardEntryAnalyticsEvent,
  resourceCardEntryDestination,
  resourceCardSourceAnalyticsData,
  resourceCardSourceAnalyticsEvent,
  resourceCardEntryKey,
  resourceCardInstallAnalyticsData,
  resourceCardInstallAnalyticsEvent,
  resourceCardInstallIntentType,
  resourceCardTrustHintAnalyticsData,
  resourceCardTrustHintAnalyticsEvent,
  type ResourceCardBadgeKind,
  type ResourceCardEntryDestination,
  type ResourceCardSurface,
  type ResourceCardVariant,
} from "@/lib/resource-card-cta-events-lib";
