/**
 * Submit flow CTA event surface.
 */
export {
  SUBMIT_SURFACE,
  submitCategorySelectAnalyticsData,
  submitCategorySelectAnalyticsEvent,
  submitCompletionEgressAnalyticsData,
  submitCompletionEgressAnalyticsEvent,
  submitDraftCopyAnalyticsData,
  submitDraftCopyAnalyticsEvent,
  submitEgressAnalyticsData,
  submitEgressAnalyticsEvent,
  submitPreflightNextActionAnalyticsData,
  submitPreflightNextActionAnalyticsEvent,
  submitPreflightRetryAnalyticsData,
  submitPreflightRetryAnalyticsEvent,
  submitStartAnalyticsData,
  submitStartAnalyticsEvent,
  submitStepAnalyticsData,
  submitStepAnalyticsEvent,
  submitSuccessAnalyticsData,
  submitSuccessAnalyticsEvent,
  type SubmitCompletionDestination,
  type SubmitDraftCopySource,
  type SubmitEgressDestination,
  type SubmitPreflightNextActionRoute,
  type SubmitStepDirection,
  type SubmitSuccessPath,
} from "@/lib/submit-cta-events-lib";
